apiVersion: v1
kind: Service
metadata:
  labels:
    app: "nextjs"
  name: "nextjs"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 80
  selector:
    app: "nextjs"
  # type: ClusterIP
  type: NodePort
